[window]
decorations = "buttonless"
opacity = 0.75
blur = false
option_as_alt = "Both"
[font]
normal = { style = "Regular", family = "Maple Mono NF CN" }
bold = { style = "Bold", family = "Maple Mono NF CN" }
italic = { style = "Italic", family = "Maple Mono NF CN" }
bold_italic = { style = "Bold Italic", family = "Maple Mono NF CN" }
size = 15
[env]
term = "xterm-256color"
[mouse]
hide_when_typing = true
[colors]
draw_bold_text_with_bright_colors = true

[[colors.indexed_colors]]
color = "0xff9e64"
index = 16

[[colors.indexed_colors]]
color = "0xdb4b4b"
index = 17

[colors.bright]
black = "0x414868"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xc0caf5"
yellow = "0xe0af68"

[colors.normal]
black = "0x15161E"
blue = "0x7aa2f7"
cyan = "0x7dcfff"
green = "0x9ece6a"
magenta = "0xbb9af7"
red = "0xf7768e"
white = "0xa9b1d6"
yellow = "0xe0af68"

[colors.primary]
background = "0x1a1b26"
foreground = "0xc0caf5"

[cursor.style]
blinking = "Always"
shape = "Block"
